M48
; DRILL file {KiCad 9.0.1} date 2025-04-27T11:51:13-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-27T11:51:13-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.170
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X108.585Y-75.311
X108.585Y-86.741
T2
X135.509Y-70.612
X135.509Y-91.44
M30
